In [63]:
# Strings
data='hello world'
print(data[0])
print(len(data))
print(data)

h
11
hello world


In [5]:
# numbers
num=123.4
print(num)
num=13
print(num)

123.4
13


In [6]:
#boolean
a=True
b=False
print(a,b)

True False


In [7]:
#Multiple assignment
a,b,c=1,2,3
print(a,b,c)

1 2 3


In [8]:
#no value or null
a=None
print(a)

None


In [17]:
#if else statement
value=90
if value>=120:
    print('this is too fast')
elif value>=80:
    print('this is fast')
else:
    print('this is safe')

this is  fast


In [18]:
#for loop
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [22]:
#while loop
i=0
while i<10:
    print(i)
    i+=1

0
1
2
3
4
5
6
7
8
9


In [23]:
#Tuple
a=(1,2,4)
print(a)

(1, 2, 4)


In [66]:
#List
mylist=[1,2,3,4]
print("first value %d"% mylist[0])
print(len(mylist))
mylist.append(5)
print("length=",len(mylist))
for value in mylist:
    print(value)

first value 1
4
length= 5
1
2
3
4
5


In [35]:
#dictionary
mydict={'a':1,'b':2,'c':3}
print('A value :',mydict['a'])
mydict['a']=12
print('A value :',mydict['a'])
print('keys=',mydict.keys())
print('values=',mydict.values())
for key in mydict.keys():
    print(mydict[key])


A value : 1
A value : 12
keys= dict_keys(['a', 'b', 'c'])
values= dict_values([12, 2, 3])
12
2
3


In [38]:
#functions
def mysum(x,y):
    return x+y
print(mysum(2,3))

5


In [46]:
#numpy - array creation
import numpy as np
mylist=[1,2,3]
print(type(mylist))
nparray=np.array(mylist)
print(type(nparray))
print(nparray)
print(nparray.shape)


<class 'list'>
<class 'numpy.ndarray'>
[1 2 3]
(3,)
[[1 2 3]
 [5 6 7]]
(2, 3)


In [59]:
# numpy - array access
mylist=[[1,2,3],[5,6,7]]
nparray=np.array(mylist)
print(nparray)
print(nparray.shape)
print("first row=",nparray[0])
print("last row=",nparray[-1])
print("specific row col=",nparray[1,1])
print("first col=",nparray[:,0])
#further divide into arrays
print("second col=",nparray[:,1:2])

[[1 2 3]
 [5 6 7]]
(2, 3)
first row= [1 2 3]
last row= [5 6 7]
specific row col= 6
first col= [1 5]
second col= [[2]
 [6]]


In [61]:
# numpy arithmetic
myarray1=np.array([1,2,3])
myarray2=np.array([5,5,5])
print("sum=",myarray1+myarray2)
print("product=",myarray1*myarray2)

sum= [6 7 8]
product= [ 5 10 15]
